### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by abbeyskinner** [stat231-f21/blog_aaa#1]
1. Do you plan for this project to be an extension of the mid-semester project?
Yes, we plan on having our blog to be an extension of our shiny app. We want to continue to focus on equity in the US health care system as we were before. 
- We would like to examine the effect of intersectionality in health inequities; given that social inequality is not shaped by a single axis of social division but by multiples factors in mutually influencing ways, intersectionality would help better understand the complexity behind health disparities.  
- After the passage of Affordable Care Act in 2010, public health insurance such as Medicaid has helped achieve some degree of health care equity by providing access to affordable, high-quality care and health coverage, regardless of one’s position in the society. Yet, there still remains room for improvement for public health insurance plans, so we would like to investigate how its quality can be improved to better address health inequities. We hope to come up with strategies for strengthening public health insurance by looking at health insurance ratings data. Additionally, we plan on also diving into the differences between private and public healthcare and the disparities between the two. 
- In order to do so, we will need at least 1 additional data set. Most likely we will use more than one and we do not think we will use our dataset from our shiny app. This is mainly because we want a state-by-state breakdown of the data and that dataset only had a location variable that separated the US into 4 regions. So for this project we are searching for datasets that have a variable with all 50 states.

2. Visualization Ideas
- To examine the role of intersectionality in health disparities, we plan to perform cluster analysis to identify social categories that drive health disparities, and create a network graph on those categories to examine how they influence each other when it comes to health inequities.
- We would also conduct text analysis on the feedback from the currently insured population and create a network graph to analyze public sentiment toward public insurance and compare the results with clients’ opinions about their private health insurance plans. 
- We would also like to create an interactive map that will indicate the amount of providers per state and when zoomed in, allow users to see the amount of providers per county. 
- Additionally, we want to create a time-series which shows the breakdown of healthcare over the years 2008-2019. For the time-series visualization, we could either create a shiny app that allows the user to select the years they would like the data to be narrowed down to or create a gif of the maps that shifts colors every second to show change in time. The dataset can also be broken into a state-by-state time series, allowing users to choose which states they would like to look at through a slider input. 

3. We plan on meeting every Sunday and Tuesday nights at 8pm. Schedule: Nov 9: Datasets chosen and Wrangled Data; Nov 16: Visualizations, Nov 22: Presentation Ready (have layout and text on blog all set + what code we want to have in our blog--start to prepare for what we will say); Nov 30: Presentation

**Comment by bebailey** [comment]
Thanks for the update! Fingers crossed you find (or have already found) a dataset that meets your needs. 

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by hailinkim** [comment]
We've chosen three datasets: health insurance coverage status, national health interview survey data, and star ratings data for Medicaid. For the health insurance coverage status, we have combined 8 different data sets, each containing data from a different year (2012-2019). It breaks down the numbers and percentages of health care status for different demographic groups. It also breaks down the data to both a county and state level. To examine how public insurance (i.e. Medicaid) could be improved, we focus on the variables related to policyholders' experience, complaints, and customer service, and the ratings associated with each variable. We also decided to keep the survey data we used for Shiny; we will look at demographic and socioeconomic variables and access to healthcare. We have all of our data sets wrangled and pushed them to our repo. We're planning to work on visualizations by this Sunday.

**Comment by abbeyskinner** [comment]
We have created 2 visualizations so far. One is the animated word cloud of policyholders' opinion about Medicare over the time period between 2016 and 2021. Another is a time series from 2012 to 2019 which shows how the percent of people who are unemployed has changed over the years by race and state. We are working on a interactive map as well and a cluster analysis. We are slightly behind our checkpoints as we had hoped to have all our visualizations done by today, however we feel that we are still in a good place. We plan to have them all done by Sunday and then we will meet on Monday to start working on the layout and setup of our blog.
